name = "adg"
description = "ada group and privilege escalation"
version = "0.1.0-dev"

authors = ["tali auster"]
maintainers = ["tali auster <tali.auster@gmail.com>"]
maintainers-logins = ["atalii"]

executables = ["adg"]
[[depends-on]]
gnatprove = "^12.1.1"
